### ISSUE TITLE
Example usage doesn't work with pip3 installation

### ISSUE THREAD

**Issue by niemasd** [veg/hivtrace#29] opened 2017-04-17 21:57 UTC
Perhaps I'm mistaken, but if you install hivtrace using pip3 (`pip3 install hivtrace`), it installs it as a Python 3 module, but not as an executable on its own. To run hivtrace, I had to make a Python 3 script as follows:

```python
#! /usr/bin/env python3
from hivtrace import hivtrace
hivtrace.main()
```

Putting this script in my `PATH` (and naming it `hivtrace`) allows me to use the tool as it is described in the README

**Comment by stevenweaver** [comment] 2017-04-18 15:47
Dear @niemasd,

May I ask which operating system and python 3 version you are using to install hivtrace?
On CentOS 7, the hivtrace binary was successfully copied to `/usr/bin/`. 

My conjecture is that this issue may have arisen out of new file system restrictions put in place by macOS 10.11, and would like to ensure that is your operating system before moving to correct the problem.

**Comment by EduanWilkinson** [comment] 2017-04-18 17:51
Im having a similar issue with HIV-TRACE

Ive successfully installed all dependencies and HIV-Trace itself. However, when I try to run I get the following error message:

ssrb-vpn1-0-54:Desktop eduan$ hivtrace -i ./hivtrace_test.aln.fasta -a 500 -r HXB2_pol -t .015 -m 500 -g .05 -c
Traceback (most recent call last):
  File "/usr/local/bin/hivtrace", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 568, in main
    results = hivtrace(ID, FN, REFERENCE, AMBIGUITY_HANDLING, DISTANCE_THRESHOLD, MIN_OVERLAP, COMPARE_TO_LANL, FRACTION, strip_drams_flag =STRIP_DRAMS, filter_edges = args.filter, handle_contaminants = args.curate, skip_alignment=args.skip_alignment)
  File "/usr/local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 335, in hivtrace
    subprocess.check_call(bealign_process, stdout=DEVNULL)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/opt/python3/bin/bealign'

Im running python3 and OS X 10.11.6

Thanks

**Comment by stevenweaver** [comment] 2017-04-18 17:56
@EduanWilkinson ,

Thank you, I am certain that this is an issue with either python3.6 or macOS 10.11. I am currently setting up an environment to reproduce the issue. 

Best,
Steven

**Comment by niemasd** [comment] 2017-04-19 06:25
Yes, I am on the newest Mac OS X, so that is probably the culprit

**Comment by EduanWilkinson** [comment] 2017-04-21 19:26
Hello Steven

What version of macOS X and python3 should I try and use. I could
potentially find a Mac in the lab with the right requirements.

Regards,
Eduan

**Comment by vagnerfonseca** [comment] 2018-02-02 21:00
Traceback (most recent call last):
  File "/bin/hivtrace", line 11, in <module>
    load_entry_point('hivtrace==0.4.0', 'console_scripts', 'hivtrace')()
  File "/usr/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 670, in main
    results = hivtrace(ID, FN, REFERENCE, AMBIGUITY_HANDLING, DISTANCE_THRESHOLD, MIN_OVERLAP, COMPARE_TO_LANL, FRACTION, strip_drams_flag =STRIP_DRAMS, filter_edges = args.filter, handle_contaminants = args.curate, skip_alignment=args.skip_alignment, attributes_file=ATTRIBUTES_FILE)
  File "/usr/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 461, in hivtrace
    subprocess.check_call(tn93_process,stdout=tn93_fh,stderr=tn93_fh)
  File "/usr/lib64/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tn93': 'tn93'

**Comment by stevenweaver** [comment] 2018-02-02 21:03
Dear @vagnerfonseca,

Did you run `make install` for tn93? tn93 needs to be in your environment path (i.e. `$PATH`).

Best,
Steven

**Comment by vagnerfonseca** [comment] 2018-02-02 21:04
yes make install

**Comment by vagnerfonseca** [comment] 2018-02-02 21:05
tn93 --version
v1.0.4

**Comment by vagnerfonseca** [comment] 2018-02-02 21:10
ok i move tn93 for /usr/bin/
``
Traceback (most recent call last):
  File "/bin/hivtrace", line 11, in <module>
    load_entry_point('hivtrace==0.4.0', 'console_scripts', 'hivtrace')()
  File "/usr/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 670, in main
    results = hivtrace(ID, FN, REFERENCE, AMBIGUITY_HANDLING, DISTANCE_THRESHOLD, MIN_OVERLAP, COMPARE_TO_LANL, FRACTION, strip_drams_flag =STRIP_DRAMS, filter_edges = args.filter, handle_contaminants = args.curate, skip_alignment=args.skip_alignment, attributes_file=ATTRIBUTES_FILE)
  File "/usr/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 461, in hivtrace
    subprocess.check_call(tn93_process,stdout=tn93_fh,stderr=tn93_fh)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tn93', '-q', '-o', '/tmp/hivtrace-p48jk4_1/hiv1.fasta_user.tn93output.csv', '-t', '.015', '-a', 'resolve', '-l', '500', '-g', '.05', '-f', 'csv', './hiv1.fasta_output.fasta']' returned non-zero exit status 1.
``

Is this result expected? I'm just installing on the server.

**Comment by stevenweaver** [comment] 2018-02-02 21:13
Dear @vagnerfonseca, 

It is not expected. I'm working on replicating the issue. 

Best,
Steven

**Comment by vagnerfonseca** [comment] 2018-02-02 21:15
ok thanks

**Comment by stevenweaver** [comment] 2018-02-02 21:17
Can you please send me the output of `which tn93`?

**Comment by vagnerfonseca** [comment] 2018-02-02 21:18
`which tn93`
`/usr/local/bin/tn93`

**Comment by stevenweaver** [comment] 2018-02-02 21:19
Dear @vagnerfonseca, 

Can you try the following command and then try again?
`export PATH=/usr/local/bin:$PATH`

Best,
Steven

**Comment by vagnerfonseca** [comment] 2018-02-02 21:20
```
Traceback (most recent call last):
  File "/bin/hivtrace", line 11, in <module>
    load_entry_point('hivtrace==0.4.0', 'console_scripts', 'hivtrace')()
  File "/usr/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 670, in main
    results = hivtrace(ID, FN, REFERENCE, AMBIGUITY_HANDLING, DISTANCE_THRESHOLD, MIN_OVERLAP, COMPARE_TO_LANL, FRACTION, strip_drams_flag =STRIP_DRAMS, filter_edges = args.filter, handle_contaminants = args.curate, skip_alignment=args.skip_alignment, attributes_file=ATTRIBUTES_FILE)
  File "/usr/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 461, in hivtrace
    subprocess.check_call(tn93_process,stdout=tn93_fh,stderr=tn93_fh)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tn93', '-q', '-o', '/tmp/hivtrace-p645elgh/hiv1.fasta_user.tn93output.csv', '-t', '.015', '-a', 'resolve', '-l', '500', '-g', '.05', '-f', 'csv', './hiv1.fasta_output.fasta']' returned non-zero exit status 1.
```

**Comment by stevenweaver** [comment] 2018-02-02 21:31
@vagnerfonseca, 

Ok, `hivtrace` seems to be properly installed, but `tn93` is throwing an exception. Can you please verify that the file `hiv1.fasta_output.fasta` is not empty or that it is a formatted fasta file?

Something along the hivtrace pipeline is malfunctioning with the input provided. In order to help further, I may need a dataset, emailed to sweaver@temple.edu, that will help me replicate the issue or at least the initial parameters used with `hivtrace`. 

Best,
Steven

**Comment by vagnerfonseca** [comment] 2018-02-02 21:39
ok i send

**Comment by smazrouee** [comment] 2018-05-22 17:43
Thank you for your quick response. I tried the installation: 
_-> pip install -t ~/miniconda3/bin/ hppy_

Seems like it's installed successfully. Below is pip freeze output: 
_asn1crypto==0.24.0
biopython==1.71
biopython-extensions==0.18.6
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
conda==4.5.4
ConsensusCore==1.0.2
cryptography==2.2.2
Cython==0.28.2
fakemp==0.9.1
hivclustering==1.3.1
hivtrace==0.1.6
hppy==0.9.9
hyphy-python==0.1.9
idna==2.6
mkl-fft==1.0.0
mkl-random==1.0.1
numpy==1.14.3
pycosat==0.6.3
pycparser==2.18
pyOpenSSL==17.5.0
pysam==0.11.2.2
PySocks==1.6.8
requests==2.18.4
ruamel-yaml==0.15.35
scipy==1.1.0
six==1.11.0
tornado==5.0.2
urllib3==1.22_

Yet, I get the same error running hivtrace: 
_pkg_resources.DistributionNotFound: The 'HyPhy>=0.1.1' distribution was not found and is required by hivtrace_

**Comment by stevenweaver** [comment] 2018-05-22 17:52
Dear @smazrouee, 

Can you please update hivtrace to the latest version of hivtrace?

`hivtrace==0.1.6` seems rather old, and I had to make a number of dependency adjustments over the past two years.

Best,
Steven

**Comment by smazrouee** [comment] 2018-05-22 18:21
Sure! I updated HIVTrace. Yet previous error still persists. Not sure what is the problem.... 

Here is the updated pip freeze: 
_asn1crypto==0.24.0
biopython==1.71
biopython-extensions==0.18.6
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
conda==4.5.4
ConsensusCore==1.0.2
cryptography==2.2.2
Cython==0.28.2
fakemp==0.9.1
hivclustering==1.3.1
hivtrace==0.4.3
hppy==0.9.9
hyphy-helper==0.9.9
hyphy-python==0.1.9
idna==2.6
mkl-fft==1.0.0
mkl-random==1.0.1
numpy==1.14.3
pycosat==0.6.3
pycparser==2.18
pyOpenSSL==17.5.0
pysam==0.14.1
PySocks==1.6.8
requests==2.18.4
ruamel-yaml==0.15.35
scipy==1.1.0
six==1.11.0
tornado==5.0.2
urllib3==1.22_

**Comment by julievakulenko94** [comment] 2019-01-26 21:58
I am having an issue very similar to the one described by EduanWilkinson. I installed HIVTrace 
and all dependencies using pip3 (pip3 install hivtrace). To run HIVTrace I made a script as niemasd described. 
python3 hivtrace_main.py  -i test.fas -a resolve -r HXB2_pol -m 890 -g/--fraction -t 4.5  -f report
Traceback (most recent call last):
  File "hivtrace_main.py", line 3, in <module>
    hivtrace.main()
  File "/home/vjulia/.local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 810, in main
    attributes_file=ATTRIBUTES_FILE)
  File "/home/vjulia/.local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 447, in hivtrace
    subprocess.check_call(bealign_process, stdout=DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bealign': 'bealign'

python3.6.1, Ubuntu 17.10

**Comment by smazrouee** [comment] 2019-04-04 04:49
hivnetworkcsv has exact same issue under anaconda env

**Comment by lixingguang** [comment] 2019-04-30 07:41
I have also the same problem:
(base) lixingguangtekiMacBook-puro:~ lixingguang$ pip3 install hivtrace
Requirement already satisfied: hivtrace in /anaconda3/lib/python3.6/site-packages (0.1.6)
Requirement already satisfied: biopython>=1.58 in /anaconda3/lib/python3.6/site-packages (from hivtrace) (1.72)
Requirement already satisfied: BioExt>=0.17.2 in /anaconda3/lib/python3.6/site-packages (from hivtrace) (0.19.5)
Collecting HyPhy>=0.1.1 (from hivtrace)
  Could not find a version that satisfies the requirement HyPhy>=0.1.1 (from hivtrace) (from versions: )
No matching distribution found for HyPhy>=0.1.1 (from hivtrace)

**Closed** 2019-12-16 20:33 UTC
Labels: bug
